config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  resources :products do
    resources :reviews
    member do
      post :favorites
      post :unfavorite
      post :add_to_cart
    end
    collection do
      get :search
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

   namespace :account do
     resources :orders
     resources :products
   end

   resources :cart_items do
     member do
       post :add_quantity
       post :remove_quantity
     end
   end
  resources :cart_items
  resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end

 resources :my_favorites
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
    ci = cart_items.build
    ci.product = product
    ci.quantity = 1
    ci.save
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum += cart_item.quantity * cart_item.product.price
      end
    end
    sum
  end

  def clean!
    cart_items.destroy_all
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product
end

app/models/my_favorite.rb
class MyFavorite < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
  before_create :generate_token
  belongs_to :user
  has_many :product_lists

  validates :billing_name, presence: true
  validates :billing_address, presence: true
  validates :shipping_name, presence: true
  validates :shipping_address, presence: true

  def generate_token
    self.token = SecureRandom.uuid
  end

  def set_payment_with!(method)
    self.update_columns(payment_method: method)
  end

  def pay!
    self.update_columns(is_paid: true)
  end

  include AASM

  aasm do
    state :order_placed, initial: true
    state :paid
    state :shipping
    state :shipped
    state :order_cancelled
    state :good_returned

    event :make_payment, after_commit: :pay! do
      transitions from: :order_placed, to: :paid
    end

    event :ship do
      transitions from: :paid,         to: :shipping
    end

    event :deliver do
      transitions from: :shipping,     to: :shipped
    end

    event :return_good do
      transitions from: :shipped,      to: :good_returned
    end

    event :cancel_order do
      transitions from: [:order_placed, :paid], to: :order_cancelled
    end
  end

end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  belongs_to :category
  has_many :my_favorites
  has_many :collectors, through: :my_favorites, source: :user
  has_many :photos
  accepts_nested_attributes_for :photos
  def self.search(search)
    where("title LIKE ? ", "%#{search}%")
    #where("description LIKE ?", "%#{search}%")
  end

end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

app/models/review.rb
class Review < ApplicationRecord
belongs_to :user
belongs_to :product
validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
  has_many :my_favorites
  has_many :favorite_products, through: :my_favorites, source: :product
  has_many :reviews
  has_many :products
  def admin?
    is_admin
  end

  def is_favorite_of?(product)
    favorite_products.include?(product)
  end

  def favorite!(product)
    favorite_products << product
  end

  def unfavorite!(product)
    favorite_products.delete(product)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def clean
    current_cart.clean!
    flash[:warning] = "已清空购物车"
    redirect_to carts_path
  end

  def checkout
    @order = Order.new
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def show
    @order = Order.find_by_token(params[:id])
    @product_lists = @order.product_lists
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.total = current_cart.total_price

    if @order.save
      current_cart.cart_items.each do |cart_item|
        product_list = ProductList.new
        product_list.order = @order
        product_list.product_name = cart_item.product.title
        product_list.product_price = cart_item.product.price
        product_list.quantity = cart_item.quantity
        product_list.save
      end
      current_cart.clean!
      OrderMailer.notify_order_placed(@order).deliver!
      redirect_to order_path(@order.token)
    else
      render 'carts/checkout'
    end
  end

def pay_with_alipay
    @order = Order.find_by_token(params[:id])
    @order.set_payment_with!("alipay")
    @order.pay!
    @order.make_payment!

    redirect_to order_path(@order.token), notice: "使用支付宝成功完成付款"
  end

  def pay_with_wechat
    @order = Order.find_by_token(params[:id])
    @order.set_payment_with!("wechat")
    @order.make_payment!

    redirect_to order_path(@order.token), notice: "使用微信成功完成付款"
  end

  def apply_to_cancel
    @order = Order.find(params[:id])
    OrderMailer.apply_cancel(@order).deliver!
    flash[:notice] = "已提交申请"

    redirect_to :back
  end

  private

  def order_params
    params.require(:order).permit(:billing_name, :billing_address, :shipping_name, :shipping_address)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.product_id = @product.id
    if @review.save
      redirect_to @product
    else
      flash[:warning] = "你的评论没填写内容耶！"
      redirect_to @product
    end
  end


  private

  def set_product
      @product = Product.find(params[:product_id])
  end

  def review_params
    params.require(:review).permit(:body, :user_id, :product_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  # 計算購物車商品總價
    def render_cart_total_price(cart)
      if session[:currency].present? # 搜尋幣值數據
        @currency_s = session[:currency]
        @currency = Currency.find_by(name: @currency_s)
        @currency.symbol + " " + cart.total_price.to_s
      else # 預設幣值為新台幣
        "$ " + cart.total_price.to_s
      end
    end

    # 計算剩餘庫存
    def render_product_quantity(product)
      @product = Product.find(product)
      @orderSum = OrderItem.where("product_id" => product).sum(:quantity)
      @product.quantity - @orderSum
    end
  def render_cart_total_price(cart)
    cart.total_price
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def render_order_paid_state(order)
    if order.is_paid?
      "已付款"
    else
      "未付款"
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def render_product_price(product)
    if session[:currency].present?
      @currency_s = session[:currency]
      @currency = Currency.find_by(name: @currency_s)
      product.price = product.price * @currency.rate
      price = @currency.symbol + " " + product.price.to_s
    else # 預設幣值為新台幣
      price = "$ " + product.price.to_s
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/checkout.html.erb
<div class="row">
  <section id="checkout">
     <div class="checkoutbox col-md-10 col-centered">
       <br>
      <p style="color:#212121;font-size:30px;text-align:center"> <i class="fa fa-th-list" aria-hidden="true"></i>购物明细 </p>
      <table class="table table-bordered col-md-10 col-centered">
        <thead>
          <tr>
            <th colspan="2">商品明细</th>
            <th>单价</th>
            <th>数量</th>
          </tr>
        </thead>
        <tbody>

          <% current_cart.cart_items.each do |cart_item| %>
            <tr>
              <td class="text-center">
                <%= link_to product_path(cart_item.product) do %>
                <% if cart_item.product.photos.present? %>
                <%= image_tag(cart_item.product.photos[0].avatar.thumb.url, class: "thumbnail") %>
              <% else %>
                <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
                <% end %>
                <% end %>
              </td>
              <td>
                <%= link_to(cart_item.product.title, product_path(cart_item.product)) %>
              </td>
              <td>
                $ <%= cart_item.product.price %>
              </td>

              <td>
                <%= cart_item.quantity %>
              </td>

            </tr>
          <% end %>

        </tbody>
      </table>
      <div class="total col-md-12 col-centered">
        <span class="pull-right">
          实付款: <i style="color:red">$<%= render_cart_total_price(current_cart) %></i>
      </div>
      <h2 style="color:#212121;font-size:30px;text-align:center">
        <i class="fa fa-address-card-o" aria-hidden="true"></i> 订单资讯
      </h2>

      <div class="order-form col-md-12 col-centered">

          <%= simple_form_for @order do |f| %>

            <legend> 订购人</legend>
            <div class="form-group col-lg-6">
              <%= f.input :billing_name  %>
            </div>
            <div class="form-group col-lg-6">
              <%= f.input :billing_address  %>
            </div>

            <legend> 收货人</legend>
            <div class="form-group col-lg-6">
             <%= f.input :shipping_name  %>
            </div>
            <div class="form-group col-lg-6">
              <%= f.input :shipping_address  %>
            </div>

          <div class="checkout">
            <%= f.submit "生成订单", class: "btn btn-lg btn-danger pull-right",
                         data: { disable_with: "Submitting..." } %>
          </div>
        <% end %>

      </div>
    </div>
  </section>
</div>

app/views/carts/index.html.erb
<div class="product-box">
  <div class="container">
    <!--=== 商品類型 & 品牌選單 ===-->
    <div class='row content-box' style="margin-top:100px;">
      <div class='col-md-12'>
        <!--=== 頁面標題 ===-->
        <h3>
          <i class='fa fa-shopping-cart'></i>
          <%= "购物车" %></h3>
        <hr/>
        <!--=== 購物車資訊 ===-->
        <div class="row">
          <!-- 如果購物車有商品，顯示商品內容 -->
          <% if current_cart.cart_items.length > 0 %>
          <%=link_to("清空购物车", clean_carts_path, method: :delete, class: 'pull-right' , data: { confirm: t('message-confirm-clear-cart') } ) %>

          <!-- 購物車列表內容 -->
          <% current_cart.cart_items.each do |cart_item| %>
          <div class="col-md-12 cart-item-box">
            <!-- 商品圖片 -->
            <% if cart_item.product.photos[0].present? %>
            <%= image_tag(cart_item.product.photos[0].avatar.thumb.url) %>
          <% else %>
            <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
            <% end %>
            <div class="name"><%= link_to(cart_item.product.title, product_path(cart_item.product)) %></div>
            <div class="price"><%= render_product_price(cart_item.product) %></div>
            <div class="count-input ">
              <%= link_to("-", remove_quantity_cart_item_path(cart_item.product_id), class: "incr-btn", method: :post) %>
              <input class="quantity" type="text" value="<%= cart_item.quantity %>">
              <%= link_to("+", add_quantity_cart_item_path(cart_item.product_id), class: "incr-btn", method: :post) %>
            </div>

            <div class="count">-
              <%= render_cart_total_price(current_cart) %></div>
            <div>
              <%= link_to cart_item_path(cart_item.product_id), method: :delete do %>
              <i class='fa fa-close'></i>
              <% end %>
            </div>
            <hr/>
          </div>
            <% end %>
              </div>
          <div class='clearfix'>
            <div class='pull-right'><%= "合计" %><%= render_cart_total_price(current_cart) %></div>
          </div>
          <!-- 購物車結帳 -->
          <div class='clearfix'>
            <div class='pull-right'><%= link_to("前往结账", checkout_carts_path, method: :post, class: 'btn btn-md btn-default') %></div>
          </div>
        <% else %>
          <div class="buy-box">
            <h3><%= "您还没有选购任何商品" %></h3>

            <br/>
            <!-- 顯示隨機推薦商品 -->

            <div class='col-md-12'>
              <%= link_to("立刻选购", products_path, class:'btn btn-lg btn-default' ) %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>