config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  resources :products do
    resources :reviews
    member do
      post :favorites
      post :unfavorite
      post :add_to_cart
    end
    collection do
      get :search
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

   namespace :account do
     resources :orders
     resources :products
   end

   resources :cart_items do
     member do
       post :add_quantity
       post :remove_quantity
     end
   end
  resources :cart_items
  resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end

 resources :my_favorites
  root 'welcome#index'
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  belongs_to :category
  has_many :my_favorites
  has_many :collectors, through: :my_favorites, source: :user
  has_many :photos
  accepts_nested_attributes_for :photos
  def self.search(search)
    where("title LIKE ? ", "%#{search}%")
    #where("description LIKE ?", "%#{search}%")
  end

end

app/controllers/account/products_controller.rb
class Account::ProductsController < ApplicationController
  before_action :authenticate_user!

  def index
    @products = current_user.favorite_products
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout "admin"
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy, :favorites, :unfavorite]
  before_action :admin_required


  def index
    @products = current_user.products.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def destroy
      @product = Product.find(params[:id])
      @product.destroy
      flash[:alert] = " product deleted"
      redirect_to  :back
    end

    def update
        @product = Product.find(params[:id])
        @product.category_id = params[:category_id]

        if params[:photos] != nil
          @product.photos.destroy_all #need to destroy old pics first
          params[:photos]['avatar'].each do |a|
            @picture = @product.photos.create(:avatar => a)
          end

          @product.update(product_params)
          redirect_to admin_products_path

        elsif @product.update(product_params)
          redirect_to admin_products_path
        else
          render :edit
        end
      end

  def new
    @product = Product.new
    @categories = Category.all.map { |c| [c.name, c.id] }
    @photo = @product.photos.build #for multi-pics
  end


  def create
    @product = Product.new(product_params)
    @product.user = current_user
    @product.category_id = params[:category_id]
    if @product.save
      if params[:photos] != nil
       params[:photos]['avatar'].each do |a|
         @photo = @product.photos.create(:avatar => a)
       end
     end
        redirect_to admin_products_path
    else
        render :new
    end
  end



  private

  def product_params
    params.require(:product).permit(:title, :category, :description, :quantity, :price, :image, :particulars, :category_id, :is_hidden)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy, :favorites, :unfavorite]

  def index
    if params[:category].present?
      @category_id = Category.find_by(name: params[:category]).id
      @products = Product.where(category_id: @category_id)
     # 排序功能
    else
    @products = case params[:order]
            when 'by_lower_bound'
              Product.order('price DESC')
            when 'by_upper_bound'
              Product.order('price ASC')
            else
              Product.where(:is_hidden => false).order('created_at DESC').paginate(:page => params[:page], :per_page => 8)
            end
    end
    if params[:search]
      @products = Product.search(params[:search])
    end

  end

  def show
    @product = Product.find(params[:id])
    @photos = @product.photos.all
    @reviews = Review.where(product_id: @product.id).order("created_at DESC")
    @review = Review.new
  end

  def add_to_cart
    @product = Product.find(params[:id])
    if !current_cart.products.include?(@product)
      current_cart.add_product_to_cart(@product)
      flash[:notice] = "你已成功将 #{@product.title} 加入购物车"
    else
      flash[:warning] = "你的购物车内已有此物品"
    end
      redirect_to :back
  end

  def favorites
    @product = Product.find(params[:id])
    if !current_user.is_favorite_of?(@product)
      current_user.favorite!(@product)
      flash[:notice] = "成功收藏，可以到我的收藏中查看"
    else
      flash[:warning] = "此商品已收藏!"
    end
      redirect_to :back
  end

  def unfavorite
    @product = Product.find(params[:id])
    if current_user.is_favorite_of?(@product)
      current_user.unfavorite!(@product)
      flash[:notice] = "已成功取消收藏!"
    else
      flash[:warning] = "此商品未被收藏!"
    end
      redirect_to :back
  end

end

app/helpers/account/products_helper.rb
module Account::ProductsHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def render_product_price(product)
    if session[:currency].present?
      @currency_s = session[:currency]
      @currency = Currency.find_by(name: @currency_s)
      product.price = product.price * @currency.rate
      price = @currency.symbol + " " + product.price.to_s
    else # 預設幣值為新台幣
      price = "$ " + product.price.to_s
    end
  end
end

app/views/admin/products/edit.html.erb
<h2>
  Edit Product
</h2>

<%= simple_form_for [:admin, @product] do |f| %>

<div class="group">
  <%= f.input :title %>
</div>



<div class="group">
  <%= f.input :description %>
</div>

<div class="group">
  <%= f.input :quantity %>
</div>

<div class="group">
  <%= f.input :price %>
</div>

<% if @product.photos.present? %>
<span>目前商品圖</span>
<br>
<% @product.photos.each do |p| %>
<%= image_tag p.avatar.thumb.url %><br>
<% end %>
<% end %>

<div class="group">
  <%= f.label :avatar %><br>
  <%= f.file_field :avatar, :multiple => true, name: "photos[avatar][]" %>
</div>
<div class="group">
<%= f.select :category_id, @categories %>
</div>
<div class="group">
<%= f.input :is_hidden %>
</div>
<div class="group">
  <%= f.input :particulars, as: :kindeditor, :label => "商品详情" %>
</div>
<%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/admin/products/index.html.erb
<h2>
  商品列表
</h2>
<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("新增产品", new_admin_product_path, class: "btn btn-primary btn-sm") %>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th width="220">Product Pic</th>
      <th>Name</th>
      <th>Price</th>
      <th width="100">
        Options</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
    <tr>
      <td>
        <% if product.is_hidden %>
        (Hidden)
      <% else %>
        (Public)
        <% end %>

        <%= product.id %>
      </td>
      <td>
        <%= link_to product_path(product) do %>
        <% if product.photos.present? %>
        <%= image_tag(product.photos[0].avatar.thumb.url, class: "thumbnail") %>
      <% else %>
        <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
        <% end %>
        <% end %>
      </td>
      <td>
        <%= product.title %>
      </td>
      <td>
        <%= product.price %>
      </td>
      <td>
        <%= link_to("Edit", edit_admin_product_path(product),class: "btn btn-sm btn-default") %>

        <%= link_to("Delete",  admin_product_path( product), class: "btn btn-sm btn-default",
                          method: :delete, data: { confirm: "Are you sure?" } )%>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/products/new.html.erb
<h2>
  New Product
</h2>

<%= simple_form_for [:admin, @product] do |f| %>

<div class="group">
  <%= f.input :title %>
</div>


<div class="group">
  <%= f.input :description %>
</div>

<div class="group">
  <%= f.input :quantity %>
</div>

<div class="group">
  <%= f.input :price %>
</div>

<div class="group">
  <%#= f.input :image, as: :file %>
  <%= f.label :avatar %><br>
  <%= f.file_field :avatar, :multiple => true, name: "photos[avatar][]" %>
</div>
<div class="group">
<%= select_tag(:category_id, options_for_select(@categories), :prompt => "类别") %>
</div>
<div class="group">
<%= f.input :is_hidden %>
</div>
<br>
<div class="group">
  <%= f.label :商品详情 %><br>
  <%= f.kindeditor :particulars , :label => "商品详情" %>
</div>
<%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/admin/products/show.html.erb
<div class="row">
  <div class="col-md-6">
    <% if @photos.present? %>
       <% @photos.each_with_index do |p, index| %>
         <% if index == 0 %>
           <%= image_tag p.avatar.medium.url %>
           <div style="letter-spacing: -8px">
         <% else %>
           <%= image_tag p.avatar.thumb.url %>
         <% end %>
       <% end %>
       </div>
     <% else %>
         <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
     <% end %>
  </div>
  <div class="col-md-6">
    <h2>
      <%= @product.title %>
    </h2>
    <div style="height:100px;">
      <p>
        <%= @product.description %>
      </p>
    </div>
    <div>
      数量 :
      <%= @product.quantity %>
    </div>
    <div class="product-price">
      ￥
      <%= @product.price %>
    </div>
    <div class="pull-right">
      <% if @product.quantity.present? && @product.quantity > 0 %>
      <%= link_to("加入购物车", add_to_cart_product_path(@product), :method => :post, :class => "btn btn-primary btn-lg btn-danger") %>
      <% else %>
      已销售一空，无法购买
      <% end %>
    </div>
  </div>
</div>