config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  resources :products do
    resources :reviews
    member do
      post :favorites
      post :unfavorite
      post :add_to_cart
    end
    collection do
      get :search
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

   namespace :account do
     resources :orders
     resources :products
   end

   resources :cart_items do
     member do
       post :add_quantity
       post :remove_quantity
     end
   end
  resources :cart_items
  resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end

 resources :my_favorites
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
    ci = cart_items.build
    ci.product = product
    ci.quantity = 1
    ci.save
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum += cart_item.quantity * cart_item.product.price
      end
    end
    sum
  end

  def clean!
    cart_items.destroy_all
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product
end

app/models/my_favorite.rb
class MyFavorite < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
  before_create :generate_token
  belongs_to :user
  has_many :product_lists

  validates :billing_name, presence: true
  validates :billing_address, presence: true
  validates :shipping_name, presence: true
  validates :shipping_address, presence: true

  def generate_token
    self.token = SecureRandom.uuid
  end

  def set_payment_with!(method)
    self.update_columns(payment_method: method)
  end

  def pay!
    self.update_columns(is_paid: true)
  end

  include AASM

  aasm do
    state :order_placed, initial: true
    state :paid
    state :shipping
    state :shipped
    state :order_cancelled
    state :good_returned

    event :make_payment, after_commit: :pay! do
      transitions from: :order_placed, to: :paid
    end

    event :ship do
      transitions from: :paid,         to: :shipping
    end

    event :deliver do
      transitions from: :shipping,     to: :shipped
    end

    event :return_good do
      transitions from: :shipped,      to: :good_returned
    end

    event :cancel_order do
      transitions from: [:order_placed, :paid], to: :order_cancelled
    end
  end

end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  belongs_to :category
  has_many :my_favorites
  has_many :collectors, through: :my_favorites, source: :user
  has_many :photos
  accepts_nested_attributes_for :photos
  def self.search(search)
    where("title LIKE ? ", "%#{search}%")
    #where("description LIKE ?", "%#{search}%")
  end

end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

app/models/review.rb
class Review < ApplicationRecord
belongs_to :user
belongs_to :product
validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
  has_many :my_favorites
  has_many :favorite_products, through: :my_favorites, source: :product
  has_many :reviews
  has_many :products
  def admin?
    is_admin
  end

  def is_favorite_of?(product)
    favorite_products.include?(product)
  end

  def favorite!(product)
    favorite_products << product
  end

  def unfavorite!(product)
    favorite_products.delete(product)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  # 計算購物車商品總價
    def render_cart_total_price(cart)
      if session[:currency].present? # 搜尋幣值數據
        @currency_s = session[:currency]
        @currency = Currency.find_by(name: @currency_s)
        @currency.symbol + " " + cart.total_price.to_s
      else # 預設幣值為新台幣
        "$ " + cart.total_price.to_s
      end
    end

    # 計算剩餘庫存
    def render_product_quantity(product)
      @product = Product.find(product)
      @orderSum = OrderItem.where("product_id" => product).sum(:quantity)
      @product.quantity - @orderSum
    end
  def render_cart_total_price(cart)
    cart.total_price
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def render_order_paid_state(order)
    if order.is_paid?
      "已付款"
    else
      "未付款"
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def render_product_price(product)
    if session[:currency].present?
      @currency_s = session[:currency]
      @currency = Currency.find_by(name: @currency_s)
      product.price = product.price * @currency.rate
      price = @currency.symbol + " " + product.price.to_s
    else # 預設幣值為新台幣
      price = "$ " + product.price.to_s
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="row">
          <div class="col-md-2 col-xs-4">
            <h4><%= "商品资讯" %></h4>
            <ul class="list-unstyled">
              <li><a href="#s"><%= "最新商品" %></a></li>
              <li><a href="#s"><%= "独家推荐" %></a></li>
              <li><a href="#s"><%= "品牌分类" %></a></li>
            </ul>
          </div>
          <div class="col-md-2 col-xs-4">
            <h4><%= "购物须知" %></h4>
            <ul class="list-unstyled">
              <li><a href="#s"><%= "关于运送" %></a></li>
              <li><a href="#s"><%= "退货方式" %></a></li>
              <li><a href="#s"><%= "常见问题" %></a></li>
            </ul>
          </div>
          <div class="col-md-2 col-xs-4">
            <h4><%= "关于我们" %></h4>
            <ul class="list-unstyled">
              <li><a href="#s"><%= "品牌故事" %></a></li>
              <li><a href="#s"><%= "媒体报道" %></a></li>
              <li><a href="#s"><%= "联络我们" %></a></li>
            </ul>
          </div>
          <div class="col-md-6 col-xs-12">
            <br/>
            <h4><%= image_tag("logo.png") %><%= t('j-and-a-select') %></h4>
            <ul class="list-unstyled">
              <p>Designed By <a href="http://xbearx1987-blog.logdown.com" target="_blank"></a> & <a href="http://anndo-blog.logdown.com" target="_blank"> </a>
              <br/>
              Copyright ©2017 </a>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar " role="navigation " style="margin-top:-30px;">
  <div class="container">
    <% if current_page?('/') %>
      <div class="navbar navbar-default navbar-fixed-top" role="navigation" id="navbar">
    <% else %>
      <div class="navbar navbar-default navbar-fixed-top show_bgcolor" role="navigation">
    <% end %>
   <div class="navbar-header">
        <a href="/" class="navbar-brand" style="font-size: 2.0em;margin-left:-40px;">易书小站</a>

          <!-- 响应式导航 -->
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
      </div>
   <div class="navbar-collapse navbar-ex1-collapse collapse" id="myNavbar">

      <ul class="navbar-form navbar-left" style="margin-left:180px;margin-top:10px;" id="search-form">
        <%= form_tag(products_path,:method => "get") do %>
        <%= text_field_tag :search, params[:search], placeholder: "" %>
        <button type="submit" class="search-icon">
          <span class="fa fa-search fa-lg"></span>
        </button>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right" style="margin-right:120px;">
        <li> <%= link_to("Home", root_path) %></li>
        <li> <%= link_to("Products", products_path) %></li>


        <li>
          <%= link_to carts_path do  %>
          购物车
          <i class="fa fa-shopping-cart"></i>
          (
          <%= current_cart.products.count %>
          )
          <% end %>
        </li>
        <% if !current_user %>
        <li><%= link_to("注册", new_user_registration_path) %></li>
        <li><%= link_to(content_tag(:i, '登入', class: 'fa fa-sign-in'), new_user_session_path) %></li>
      <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">

            Hi!, <%= current_user.name %>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <% if current_user.admin? %>
            <li>
              <%= link_to("商家界面", admin_products_path,class: "li-style") %>
            </li>
            <% end %>
            <li>
              <%= link_to("我的收藏".html_safe, account_products_path,class: "li-style") %>
            </li>
            <li>
              <%= link_to("订单列表", account_orders_path,class: "li-style") %>
            </li>
            <li>
              <%= link_to(content_tag(:i, '登出', class: 'fa fa-sign-out'), destroy_user_session_path, method: :delete,class: "li-style") %>
            </li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JDstore 后台</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "common/navbar" %>
    <div class="row">
      <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked" style="max-width: 300px;">
          <li> <%= link_to("Products", admin_products_path) %> </li>
          <li> <%= link_to("Orders", admin_orders_path) %> </li>
        </ul>
      </div>
      <div class="col-md-10">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jdstore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <script src="https://qiyukf.com/script/ea419df8e53dcc696e4ddb9c2bfd42c1.js" defer async></script>
  <body>
    <div class="container-fluid">
      <div class="row">
        <%= render "common/navbar" %>

        <%= render "common/flashes" %>

        <%= yield %>
      </div>
    </div>
    <%= render "common/footer" %>
  </body>
</html>